-- Run with: luau tests/queue_state.spec.lua
local State = require("../src/ServerScriptService/Town/QueueState")
local Policy = require("../src/ServerScriptService/Town/QueueConfig")
local destination = { MinPlayers = 2, MaxPlayers = 4 }
local tests = 0
local function test(name, fn)
	fn()
	tests += 1
	print("PASS " .. name)
end
local function ticket(id, userId, jobId, time)
	return { id = id, userId = userId, jobId = jobId, joinedAt = time, seenAt = time }
end
local function seed(count)
	local state = State.New()
	for i = 1, count do State.Join(state, ticket("t" .. i, i, i % 2 == 0 and "server-A" or "server-B", 100 + i), 48) end
	return state
end

test("duplicate join is idempotent and cannot overwrite another server's session", function()
	local state = seed(1)
	assert(State.Join(state, ticket("t1", 1, "server-B", 101), 48))
	assert(not State.Join(state, ticket("other", 1, "server-C", 102), 48))
	assert(State.Count(state) == 1 and state.tickets["1"].id == "t1")
end)
test("old session cancellation cannot remove a newer session", function()
	local state = seed(1)
	assert(not State.Remove(state, 1, "stale"))
	assert(State.Count(state) == 1)
	assert(State.Remove(state, 1, "t1"))
end)
test("queue admission stays bounded", function()
	local state = seed(48)
	assert(not State.Join(state, ticket("t49", 49, "server-C", 110), 48))
	assert(State.Count(state) == 48)
end)
test("minimum size and batch delay are respected", function()
	local state = seed(1)
	assert(not State.Claim(state, 120, "A", "m1", destination, Policy))
	State.Join(state, ticket("t2", 2, "B", 102), 48)
	assert(not State.Claim(state, 105, "A", "m1", destination, Policy))
	assert(State.Claim(state, 114, "A", "m1", destination, Policy))
end)
test("two competing servers claim disjoint groups from the same global queue", function()
	local state = seed(8)
	assert(State.Claim(state, 110, "A", "m1", destination, Policy))
	assert(State.Claim(state, 110, "B", "m2", destination, Policy))
	local a, b = 0, 0
	for _, t in pairs(state.tickets) do
		if t.matchId == "m1" then a += 1 else assert(t.matchId == "m2") b += 1 end
	end
	assert(a == 4 and b == 4)
	assert(not State.Claim(state, 120, "C", "m3", destination, Policy))
end)
test("FIFO remains stable across different source servers", function()
	local state = seed(6)
	State.Claim(state, 120, "A", "m1", destination, Policy)
	for i = 1, 4 do assert(state.tickets[tostring(i)].matchId == "m1") end
	assert(not state.tickets["5"].matchId and not state.tickets["6"].matchId)
end)
test("only the reservation owner can commit; every source sees the same code", function()
	local state = seed(4)
	State.Claim(state, 110, "A", "m1", destination, Policy)
	assert(not State.Commit(state, "m1", "B", "wrong", 111, destination, Policy))
	assert(State.Commit(state, "m1", "A", "reserved-code", 111, destination, Policy))
	assert(state.matches.m1.code == "reserved-code" and state.matches.m1.launchAt == 116)
	assert(not State.Commit(state, "m1", "A", "other-code", 112, destination, Policy))
	assert(not State.Abort(state, "m1", "A"))
end)
test("cancel during reservation aborts a group below its minimum", function()
	local state = seed(2)
	State.Claim(state, 114, "A", "m1", destination, Policy)
	State.Remove(state, 2, "t2")
	assert(not State.Commit(state, "m1", "A", "code", 115, destination, Policy))
	assert(not state.matches.m1 and not state.tickets["1"].matchId)
end)
test("failed reservations release members to the original queue order", function()
	local state = seed(4)
	State.Claim(state, 110, "A", "m1", destination, Policy)
	assert(State.Abort(state, "m1", "A"))
	assert(#State.Waiting(state) == 4)
	assert(State.Waiting(state)[1].id == "t1")
end)
test("a crashed coordinator's lease expires; a late commit cannot resurrect it", function()
	local state = seed(4)
	State.Claim(state, 110, "A", "m1", destination, Policy)
	for _, t in pairs(state.tickets) do State.Heartbeat(state, t.userId, t.id, 139) end
	State.Prune(state, 141, Policy)
	assert(not state.matches.m1 and #State.Waiting(state) == 4)
	assert(not State.Commit(state, "m1", "A", "late-code", 142, destination, Policy))
end)
test("dead source servers are pruned and heartbeats cannot resurrect removed tickets", function()
	local state = seed(2)
	State.Heartbeat(state, 2, "t2", 140)
	State.Prune(state, 147, Policy)
	assert(not state.tickets["1"] and state.tickets["2"])
	State.Heartbeat(state, 1, "t1", 148)
	assert(not state.tickets["1"])
end)
test("expired ready transfers are removed rather than put into a second match", function()
	local state = seed(4)
	State.Claim(state, 110, "A", "m1", destination, Policy)
	State.Commit(state, "m1", "A", "code", 111, destination, Policy)
	for _, t in pairs(state.tickets) do State.Heartbeat(state, t.userId, t.id, 230) end
	State.Prune(state, 232, Policy)
	assert(State.Count(state) == 0 and not state.matches.m1)
end)
test("UpdateAsync replay does not mutate its prior value", function()
	local previous = seed(4)
	local first, retry = State.Clone(previous), State.Clone(previous)
	State.Claim(first, 110, "A", "m1", destination, Policy)
	State.Claim(retry, 110, "A", "m1", destination, Policy)
	assert(not previous.matches.m1 and not previous.tickets["1"].matchId)
	assert(first.tickets["1"].matchId == retry.tickets["1"].matchId)
end)
test("active match limit prevents unbounded reservation records", function()
	local state = seed(24)
	for i = 1, Policy.MaxActiveMatches do assert(State.Claim(state, 125, "A", "m" .. i, destination, Policy)) end
	assert(not State.Claim(state, 125, "A", "overflow", destination, Policy))
end)
print(string.format("%d queue invariants passed", tests))
